### ISSUE TITLE
I can't install high_genius_lib_hg_wsi_tookit-1.1.2.16.vip

### ISSUE THREAD

**Issue by YutaYoshino** [studica/studica-docs-worldskills#26]
In LabVIEW Setup » Installing the Toolkits
When I tried to install high_genius_lib_hg_wsi_tookit-1.1.2.16.vip, the following popup was output and I could not install it correctly.

![image](https://user-images.githubusercontent.com/118231863/201800980-5621325f-d772-49e8-b172-554599cc9cdc.png)

I would appreciate it if you could let me know if you have any information and solutions for this problem.

**Comment by ktyubeshi** [comment]
This is due to the fact that the "high_genius_lib_hg_wsi_tookit-1.1.2.16.vip" contains Chinese file names.
A rebuild of the package by Stuica is required to enable proper installation with VIPM.

![image](https://user-images.githubusercontent.com/1130122/203887142-defd2193-0da9-4207-983a-22caa9cde471.png)

![image](https://user-images.githubusercontent.com/1130122/203886801-120c7434-cc4d-4122-8f47-06a6a7814112.png)

---

Although not an official installation method, the "vip" file can be unzipped as a ZIP file.
The toolkit can be used by manually copying the files to a predetermined location while observing the contents described in the "spec" file stored directly under the unzipped directory.

**However, please do this only if you are confident that you can solve all problems caused by this method by yourself.
(In the worst case, you may need to reinstall LabVIEW.)**

In addition to package information, the spec file describes where each set of files is copied to. The path of the copy destination is the path described in the Target Dir key, and File x is a relative path with respect to the Target Dir.

For example, vi.lib in FileGroup0 is copied as shown below.
Target Dir = "\<application\>"  means the LabVIEW installation location.
![image](https://user-images.githubusercontent.com/1130122/203893572-1f0dc186-167c-498a-b466-38215e1249f9.png)

![image](https://user-images.githubusercontent.com/1130122/203893647-1a65e972-ac46-49f5-8c54-e0f018f0e444.png)

Copy the other items in the same manner, checking the description in the spec file.

The meaning of the LabVIEW installation directory is explained in the following document
https://www.ni.com/docs/ja-JP/bundle/labview/page/lvconcepts/organization_of_labview.html

Finally, I believe the Chinese file names are garbled, so rename them as necessary to fix the broken references.

The garbled state and the correct name are as follows
"vi.lib/High Genius/HG_WSI_Tookit/SubVIs/ｵ･ｲｽﾗ・vi"
"vi.lib/High Genius/HG_WSI_Tookit/SubVIs/ﾆｯｰｴﾅ･.vi"
"vi.lib/High Genius/HG_WSI_Tookit/SubVIs/ﾋｫｺ・篌ﾃﾕ.vi"

"vi.lib/High Genius/HG_WSI_Tookit/SubVIs/单步坐标.vi"
"vi.lib/High Genius/HG_WSI_Tookit/SubVIs/启动按钮.vi"
"vi.lib/High Genius/HG_WSI_Tookit/SubVIs/双红外后矫正.vi"

A clue to the correct filename can be obtained by opening HG_WSI_Tookit 1.1.2.4.lvproj in a text editor. (lvproj is encoded in UTF-8, so the original filename is preserved).

However, even after correcting the garbled file name to a Chinese file name, the LabVIEW project explorer could not handle it correctly in my environment. I would rename it to the English translated name and then fix the broken reference.
Expand all tree hierarchies in the Project Explorer, open items with warning marks, and fix all problems.

**Comment by YutaYoshino** [comment]
Thank you for the information.
We have confirmed garbled characters in our program.
Based on the above content, I will try to solve the error here as well.
